### ISSUE TITLE
AICommandSettings.asset

### ISSUE THREAD

**Issue by Noisk8** [keijiro/ScriptGeneratorTest#25] opened 2023-03-24 18:27 UTC
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!114 &1
MonoBehaviour:
  m_ObjectHideFlags: 61
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 0}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: e3fa2649d95d04f44a7953dfbf94acfb, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  apiKey: here havemy api key
  timeout: 0

what is wrong with the code???

**Comment by Noisk8** [comment] 2023-03-24 18:38
![ERROR API KEY](https://user-images.githubusercontent.com/17709296/227611522-2524d6e6-4a01-4ab1-8b64-deb641dd9280.png)

**Comment by keijiro** [comment] 2023-03-25 00:52
Please try removing `UserSettings` directory and start over from Project Settings.

(Close Unity Editor before removing the directory)

**Comment by Noisk8** [comment] 2023-03-25 21:10
Thanks

**Comment by andrewlaboy** [comment] 2023-03-27 02:45
@Noisk8 @keijiro the issue is the Unity version. I tried opening in 2022.2, same error. Tried editing the asmdef to get rid of Mac Standalone not supported error, and more errors of missing namespaces appeared. Switched to 2023 beta that Keijiro is on and it works.

**Comment by keijiro** [comment] 2023-03-27 03:06
I close this issue now. Please reopen it if it still reproduces.

**Closed as completed by keijiro** 2023-03-27 03:06 UTC
Labels: question
