### ISSUE TITLE
Null Reference Exception 2

### ISSUE THREAD

**Issue by Liferocka** [keijiro/ScriptGeneratorTest#10] opened 2023-03-20 07:08 UTC
Im trying the default prompt you have in there, random cubes. etc. ( I forget what it said) I get and error. Null Reference Exception  "Object reference is not set to an instance of an object... I made a cube object and then asked the AI to copy "cube" fout times and got another Null. ?

**Comment by keijiro** [comment] 2023-03-20 07:11
Could you check FAQ on README? ("AICommandWindow throws NullReferenceException")

**Comment by Liferocka** [comment] 2023-03-20 07:12
I did check that, I saw that.I still dont know what you mean?

**Comment by Liferocka** [comment] 2023-03-20 07:13
Oh I get it, I have not paid for OpenAI, ChatGPT.  I only have the free version. So I wont be able to use this correct?

**Comment by keijiro** [comment] 2023-03-20 07:15
You can try it without paying if your free trial period is still valid. I guess it has expired, though.

**Comment by Liferocka** [comment] 2023-03-20 07:16
My free trial is still taking my text prompts. its still gives me chat back.. hmm. is this the same as "free trial".. . Im signing into my Open I account and Im able to go feedback.

**Comment by keijiro** [comment] 2023-03-20 07:20
I'd recommend asking ChatGPT about it.

(I'm not kidding... It's quite good at that kind of troubleshooting. At least, it's good at English than me.)

**Comment by keijiro** [comment] 2023-03-20 07:20
I close this issue as resolved. Please reopen it for further technical problems.

**Comment by Liferocka** [comment] 2023-03-20 07:30
Please, I would really like to try this. I asked ChatGPT, its says it cannot look into my account.    I still have credit in my account for the free trial. I only used it a few times... do you know of any other reasons why I would get these errors? 
this seems to show I have usage left right? https://www.dropbox.com/s/z1o9l6mfpc7pduf/Screen%20Shot%202023-03-20%20at%203.28.48%20AM.png?dl=0

**Comment by keijiro** [comment] 2023-03-20 08:15
According to the screenshot you attached, your free trial usage has expired on 1st January 2023.

**Comment by Nanobrainiac** [comment] 2023-03-20 08:18
> I'd recommend asking ChatGPT about it.
> 
> (I'm not kidding... It's quite good at that kind of troubleshooting. At least, it's good at English than me.)

Too funny! But its true.

**Comment by keijiro** [comment] 2023-03-20 08:19
I close again because the root cause is clear now (your trial period has expired).

Please reopen it if it still reproduces after registering a valid credit card.

**Closed as completed by keijiro** 2023-03-20 08:19 UTC
Labels: question

**Comment by Liferocka** [comment] 2023-03-20 08:38
Ok, thanks. Yes

**Comment by Nanobrainiac** [comment] 2023-03-20 08:40
@Liferocka 

Let's collab. Where can I message you? I'll pay for an account.

**Comment by Liferocka** [comment] 2023-03-21 03:26
> @Liferocka
> 
> Let's collab. Where can I message you? I'll pay for an account.
@Nanobrainiac 
Hey, good to hear from you, Im down. I am only learning Unity recely but moving along. I am a 3D artist. I make 1/1 NFTs. so I use Unity to Upload custom Avatars into Spatial.io the metaverse platform. they have a Spatial SDK. Im not super advanced at all in Unity, and to be honest, I dont know scripting at all, this is why I like this I, so, I figure t may help me in soem of the scripting I cant do .  With all that said, hit me up on IG @brianlife or my email  brianlifeis@gmail.com

**Comment by keijiro** [comment] 2023-03-21 04:42
I freeze this thread. Please use a private channel for personal communication.
